package Remedy::Form::TicketGen;
our $VERSION = "0.12";
# Copyright and license are in the documentation below.

=head1 NAME

Remedy::Form::TicketGen - ticket-generation table

=head1 SYNOPSIS

    use Remedy::Form::TicketGen;

    my $inc_num = Remedy::TicketGen[...]

    use Remedy::TicketGen;

    # $remedy is a Remedy object
    my @kk
    my @worklog = Remedy::TicketGen->select (
        'db' => $remedy, 'TicketGen' => 'INC000000002371');
    for my $wl (@worklog) { print scalar $wl->print_text }

=head1 DESCRIPTION

Stanfor::Remedy::Unix::TicketGen tracks individual work log entries for tickets as part
of the remedy database.  It is a sub-class of B<Stanford::Packages::Form>, so
most of its functions are described there.

=cut

##############################################################################
### Configuration 
##############################################################################

our $DEFAULT_DESC = "Generated by __PACKAGE__";

##############################################################################
### Declarations
##############################################################################

use strict;
use warnings;

use Remedy::Form qw/init_struct/;

our @ISA = init_struct (__PACKAGE__);
Remedy::Form->register ('ticketgen', __PACKAGE__);

##############################################################################
### Class::Struct
##############################################################################

=head1 FUNCTIONS

These 

=head2 B<Class::Struct> Accessors

=over 4

=item description ($)

=item incnum ($)

=item submitter ($)

=back

=cut

##############################################################################
### Local Functions 
##############################################################################

=head2 B<Remedy::Form Overrides>

=over 4

=item field_map

=cut

sub field_map { 
    'inc_num'     => "Incident Number",
    'status'      => "Status",
    'submitter'   => "Submitter",
    'description' => "Short Description",
}

=item table ()

F<HPD:CFG Ticket Num Generator>

=cut

sub table { 'HPD:CFG Ticket Num Generator' }

=back

=cut

###############################################################################
### Final Documentation
###############################################################################

=head1 REQUIREMENTS

B<Class::Struct>, B<Remedy::Form>

=head1 SEE ALSO

Remedy(8)

=head1 HOMEPAGE

TBD.

=head1 AUTHOR

Tim Skirvin <tskirvin@stanford.edu>

=head1 LICENSE

Copyright 2008-2009 Board of Trustees, Leland Stanford Jr. University

This program is free software; you may redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
